/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: test.twee
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @test: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@test()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage0_Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #0: StoryTitle

	void passage0_Init()
	{
		this.Passages[@"StoryTitle"] = new StoryPassage(@"StoryTitle", new string[]{  }, passage0_Main);
	}

	IStoryThread passage0_Main()
	{
		yield return text(@"Untitled Story");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #1: hugo 03

	void passage1_Init()
	{
		this.Passages[@"hugo 03"] = new StoryPassage(@"hugo 03", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"Hugo: Você vai ficar por aqui mais um pouco, né? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Porque eu e mamãe tinhamos planejado almoçar daqui a pouco, e ela queria que todo mundo fosse junto.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Sim Hugo, não preocupa. Eu encontro com sua mãe e nós vamos pro restaurante, tá bom?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo. Tá bom então, até mais tarde.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: hugo 02

	void passage2_Init()
	{
		this.Passages[@"hugo 02"] = new StoryPassage(@"hugo 02", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"OL: Eu não sabia que você entendia tanto sobre navios assim.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Não, nem entendo não, mãe... ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Isso aí é coisa do Gabriel, foi ele que me contou. Seu neto é muito inteligente.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: E falando nisso, você viu ele por aí? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Ele sumiu depois do café da manhã, e tá quase na hora do remédio dele, não sei se ele lembrou.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Eu devia ir atrás dele...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Bom, pode ir.", @"hugo 03", null);
		yield return lineBreak();
		yield return link(@"Deixa que eu vou.", @"hugo 04", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: StoryAuthor

	void passage3_Init()
	{
		this.Passages[@"StoryAuthor"] = new StoryPassage(@"StoryAuthor", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"Anonymous");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: hugo 04

	void passage4_Init()
	{
		this.Passages[@"hugo 04"] = new StoryPassage(@"hugo 04", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"Hugo: Bem, então toma o aqui o remédio.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: E quando você achar ele, lembra que a gente vai almoçar daqui a pouco, mamãe que disse.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Sim, tudo bem.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: Start

	void passage5_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"Hugo: E então Mãe, o que a senhora achou? O navio é muito bonito, né?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: É... é bonitinho sim.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Sabia que ele é um dos 4 navios de cruzeiro a dar uma volta completa no mundo de uma vez só? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"E que ele também o deck de observação mais logo entre os navios antigos, da classe D277?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Hm, interessante...", @"hugo 01", null);
		yield return lineBreak();
		yield return link(@"como você sabe disso?", @"hugo 02", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: hugo 05

	void passage6_Init()
	{
		this.Passages[@"hugo 05"] = new StoryPassage(@"hugo 05", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"OL:Eu acho que eles fecharam a piscina, teve um alerta de mau tempo ou algo assim.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Mau tempo? Mas o céu tá azulzinho, não tem nenhuma nuvem! Não é possível!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Eu preciso descobrir o quê que tá acontecendo.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Eu posso procurar o rapaz que me disse isso, ele deve estar no pátio central ainda.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Não mãe, pode deixar que eu vou resolver isso!");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: hugo 01

	void passage7_Init()
	{
		this.Passages[@"hugo 01"] = new StoryPassage(@"hugo 01", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"Hugo: E que ele também é um dos poucos que mantém a maior parte da tripulação no mesmo navio por... ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Você não quer saber, né?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Hm, pode continuar, não tem problema.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Não, pode deixar. Desculpa se eu tava te incomodando.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Hugo: Bem, eu vou subir pras piscinas agora, você quer ir comigo?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Agora não dá.", @"hugo 05", null);
		yield return lineBreak();
		yield return link(@"Sim, vamos!", @"hugo 06", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: hugo 06

	void passage8_Init()
	{
		this.Passages[@"hugo 06"] = new StoryPassage(@"hugo 06", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"Hugo: Você viu um mapa por aí? Eu ainda tô meio perdido aqui dentro, esse navio é muito grande!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Não, mas eu sei pra onde a gente tem que ir.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"OL: Eu acho.");
		yield return lineBreak();
		yield break;
	}


}